name: Build

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/build.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Build Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: ${{ matrix.image }}
          load: true
          pull: true
          push: false
          tags: "wildwildangel/apifuzzer:${{ github.sha }},wildwildangel/apifuzzer:latest"

      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "wildwildangel/apifuzzer:${{ github.sha }}"
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: (github.event_name != 'push' || github.ref == 'refs/heads/master')

      - name: Push the image
        run: |
          docker push "wildwildangel/apifuzzer:${{ github.sha }}"
          docker push "wildwildangel/apifuzzer:latest"
        if: (github.event_name != 'push' || github.ref == 'refs/heads/master')
