name: Build

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/build.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and push Docker image
    permissions:
      contents: read
      security-events: write
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@95cb08cb2672c73d4ffd2f422e6d11953d2a9c70 # tag=v2.1.0

      - name: Build Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # tag=v3.2.0
        with:
          context: ${{ matrix.image }}
          load: true
          pull: true
          push: false
          tags: "wildwildangel/apifuzzer:${{ github.sha }},wildwildangel/apifuzzer:latest"

      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "wildwildangel/apifuzzer:${{ github.sha }}"
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@807578363a7869ca324a79039e6db9c843e0e100 # tag=v2
        with:
          sarif_file: trivy-results.sarif

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: (github.event_name != 'push' || github.ref == 'refs/heads/master')

      - name: Push the image
        run: |
          docker push "wildwildangel/apifuzzer:${{ github.sha }}"
          docker push "wildwildangel/apifuzzer:latest"
        if: (github.event_name != 'push' || github.ref == 'refs/heads/master')
