name: Build

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/build.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and push Docker image
    permissions:
      contents: read
      security-events: write
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # tag=v2.2.1

      - name: Build Docker image
        uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3 # v3.3.0
        with:
          context: ${{ matrix.image }}
          load: true
          pull: true
          push: false
          tags: "wildwildangel/apifuzzer:${{ github.sha }},wildwildangel/apifuzzer:latest"

      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "wildwildangel/apifuzzer:${{ github.sha }}"
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@515828d97454b8354517688ddc5b48402b723750 # v2
        with:
          sarif_file: trivy-results.sarif

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: (github.event_name != 'push' || github.ref == 'refs/heads/master')

      - name: Push the image
        run: |
          docker push "wildwildangel/apifuzzer:${{ github.sha }}"
          docker push "wildwildangel/apifuzzer:latest"
        if: (github.event_name != 'push' || github.ref == 'refs/heads/master')
