name: Build

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/build.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and push Docker image
    permissions:
      contents: read
      security-events: write
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0

      - name: Build Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          context: ${{ matrix.image }}
          load: true
          pull: true
          push: false
          tags: "wildwildangel/apifuzzer:${{ github.sha }},wildwildangel/apifuzzer:latest"

      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "wildwildangel/apifuzzer:${{ github.sha }}"
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@67a35a08586135a9573f4327e904ecbf517a882d # v2
        with:
          sarif_file: trivy-results.sarif

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: (github.event_name != 'push' || github.ref == 'refs/heads/master')

      - name: Push the image
        run: |
          docker push "wildwildangel/apifuzzer:${{ github.sha }}"
          docker push "wildwildangel/apifuzzer:latest"
        if: (github.event_name != 'push' || github.ref == 'refs/heads/master')
